apiVersion: v1
kind: Secret
metadata:
  name: quay-minio-config-bundle
  namespace: quay-registry # <-- Your Quay namespace
stringData:
  config.yaml: |
    DISTRIBUTED_STORAGE_CONFIG:
      default:
        - RadosGWStorage # actual driver
        - access_key: 'minio'
          secret_key: 'minio123'
          bucket_name: 'quay-registry-bucket'
          hostname: '<REPLACE_ME_WITH_MINIO_API_ROUTE>'
          is_secure: true
          #port: '9000'
          storage_path: /datastorage/registry

    DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS:
      - default

    DISTRIBUTED_STORAGE_PREFERENCE:
      - default